### ISSUE TITLE
Embaded function for docker image builds.

### ISSUE THREAD

**Issue by johnkk84** [piotrsobczakwro/test-github-actions#2]
Hi Piotr,
There is embaded function for build images you don't need to use run stanza:)

Here is my example.

```yaml
###
# Configure builders
###
    - uses: docker/setup-buildx-action@v1
      id: backend
    
    - uses: docker/setup-buildx-action@v1
      id: frontend

    - name: Builder backstage backend
      run: echo ${{ steps.backend.outputs.name }}
     
    - name: Builder backstage frontend
      run: echo ${{ steps.frontend.outputs.name }}

###
# Backstage backend
###
    - name: Extract metadata (tags, labels) for Docker for backage-frontend
      id: backend-meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backstage-backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Build and push Docker image backstage-backend
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.backend.outputs.name }}
        context: ${{ env.BUILD_DIR }}
        file: ${{ env.BUILD_DIR }}/Dockerfile.app
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.backend-meta.outputs.tags }}
        labels: ${{ steps.backend-meta.outputs.labels }}
```

Cheers JK
